version: '3.7'

volumes:
    logs:
        driver: local

services:
    application:
        image: php:7.4-alpine
        command: php -S 0.0.0.0:8081 -t public
        working_dir: /var/www
        environment:
            docker: "true"
        ports:
            - "8081:8081"
        volumes:
            - .:/var/www
            - ./storage/logs:/var/logs
